# name of the workflow
name: Scraper latest data 

# trigger point
# on push/on clicking workflow dispatch button/on schedule every 5 mins
on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '*/5 * * * *'

# all commands Action will execute for the push
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Prepare the environment
    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    # Step 2: Get the latest data and store it as a CSV
    - name: Fetch latest data
      run: |-        
        curl "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.csv" -o usgs_current.csv
    # Step 3: Commit and push
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACTIONS_SECRET }}
        branch: ${{ github.ref }}
    - name: Commit and push
      run: |-
        git config user.name "Automated"
        git config user.email "abhi_8@rocketmail.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
